### ISSUE TITLE
ClassCastException when handling InverseOf 

### ISSUE THREAD

**Issue by linkvt** [VisualDataWeb/OWL2VOWL#6]
See here: VisualDataWeb/WebVOWL#16

Importing this ontology fails: http://purl.obolibrary.org/obo/ro.owl
Stacktrace:
```
uk.ac.manchester.cs.owl.owlapi.OWLObjectInverseOfImpl cannot be cast to org.semanticweb.owlapi.model.OWLNamedObject
java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLObjectInverseOfImpl cannot be cast to org.semanticweb.owlapi.model.OWLNamedObject
	at de.uni_stuttgart.vis.vowl.owl2vowl.parser.GeneralPropertyParser.retrieveSuperProperties(GeneralPropertyParser.java:186)
	at de.uni_stuttgart.vis.vowl.owl2vowl.parser.ObjectPropertyParser.execute(ObjectPropertyParser.java:158)
	at de.uni_stuttgart.vis.vowl.owl2vowl.parser.GeneralParser.handleObjectProperty(GeneralParser.java:250)
	at de.uni_stuttgart.vis.vowl.owl2vowl.Converter.convert(Converter.java:121)
	...
```

**Comment by BlackDark** [comment]
Under work on [Architecture change branch](https://github.com/VisualDataWeb/OWL2VOWL/tree/architecture_change)
